import Navbar from "@/app/components/web/navbar/Navbar"
export const metadata: Metadata = {
    title: "Movies",
    description: "Generated by create next app",
};
export default function MoviesLayout({
    children, // will be a page or nested layout
}: {
    children: React.ReactNode
}) {
    return (
        <section>
            {/* Include shared UI here e.g. a header or sidebar */}
            <Navbar />
            <div className="relative isolate px-6 pt-14 lg:px-8">
                {children}
            </div>
        </section>
    )
}